# Generated by Django 6.0.5 on 2026-06-08 21:52

import django.db.models.deletion
import django.utils.timezone
import utils.enum
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Display',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('visibility', models.CharField(choices=utils.enum.PostVisibility.choices, db_index=True, default='public', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('reshares_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displays', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='displays', to='medias.media')),
                ('reshare_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reshares', to='displays.display')),
            ],
            options={
                'db_table': 'displays_display',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayComment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('body', models.TextField(max_length=1000)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_comments', to=settings.AUTH_USER_MODEL)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='displays.display')),
            ],
            options={
                'db_table': 'displays_display_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisplayLike',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='displays.display')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='display_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'displays_display_like',
            },
        ),
        migrations.CreateModel(
            name='DisplayView',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='displays.display')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='display_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'displays_display_view',
            },
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['author', '-created_at'], name='display_author_created_idx'),
        ),
        migrations.AddIndex(
            model_name='display',
            index=models.Index(fields=['expires_at', 'is_deleted'], name='display_expiry_cleanup_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='displaylike',
            unique_together={('user', 'display')},
        ),
        migrations.AlterUniqueTogether(
            name='displayview',
            unique_together={('user', 'display')},
        ),
    ]
