# Generated by Django 6.0.5 on 2026-05-24 16:31

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='back_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_back', to='medias.media'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='front_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_front', to='medias.media'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_selfie', to='medias.media'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_record', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='successful_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_avatars', to='medias.media'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_covers', to='medias.media'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='user',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='user_search_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referral_code'], name='user_referral_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['referred_by'], name='user_referred_by_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='user_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=['email'], name='user_active_email_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following', 'status'], name='follow_following_status_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'status'], name='follow_follower_status_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(condition=models.Q(('status', 'accepted')), fields=['follower'], name='follow_accepted_follower_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(condition=models.Q(('status', 'accepted')), fields=['following'], name='follow_accepted_following_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddIndex(
            model_name='kyc',
            index=models.Index(fields=['status'], name='kyc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='kyc',
            index=models.Index(fields=['submitted_at'], name='kyc_submitted_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['user', 'purpose', 'is_used'], name='otp_user_purpose_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='otp_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(condition=models.Q(('is_used', False)), fields=['user', 'purpose'], name='otp_active_idx'),
        ),
        migrations.AddIndex(
            model_name='referral',
            index=models.Index(fields=['referrer', 'reward_granted'], name='referral_reward_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user', 'is_deleted'], name='device_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['last_seen_at'], name='device_last_seen_brin_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userdevice',
            unique_together={('user', 'device_fingerprint')},
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=models.Index(fields=['user', '-created_at'], name='location_user_latest_idx'),
        ),
        migrations.AddIndex(
            model_name='userlocation',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='location_created_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='profile_search_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_verified'], name='profile_verified_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['is_private'], name='profile_private_idx'),
        ),
    ]
