# Generated by Django 6.0.5 on 2026-05-27 23:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_connection'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsRewarding',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('points', models.PositiveIntegerField()),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('source_object_id', models.UUIDField(db_index=True)),
                ('is_claimed', models.BooleanField(db_index=True, default=False)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_point_reward',
                'indexes': [models.Index(fields=['user', 'is_claimed'], name='reward_user_claimed_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='reward_source_idx')],
            },
        ),
    ]
