# Generated by Django 6.0.5 on 2026-10-10 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_search_triggers_and_trgm'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPhoneCatalog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('phone_serial_no', models.CharField(max_length=150)),
                ('phone_type', models.CharField(max_length=50)),
                ('phone_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_catalog_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user phone catalog',
                'db_table': 'accounts_user_phone_catalog',
                'indexes': [models.Index(fields=['phone_name'], name='phone_catalog_name_idx'), models.Index(fields=['user'], name='phone_catalog_user_idx')],
            },
        ),
    ]
