# Generated by Django 6.0.5 on 2026-05-24 16:31

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import utils.enum
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collection',
                'db_table': 'media_collection',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('media_type', models.CharField(choices=utils.enum.MediaType.choices, db_index=True, max_length=10)),
                ('visibility', models.CharField(choices=utils.enum.MediaVisibility.choices, db_index=True, default='public', max_length=10)),
                ('storage_key', models.CharField(help_text='S3 / R2 object key. Never expose this directly.', max_length=512, unique=True)),
                ('cdn_url', models.TextField(blank=True, help_text='CDN-fronted public URL; empty until processing completes.')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('blurhash', models.CharField(blank=True, help_text='BlurHash string for low-res placeholder.', max_length=100)),
                ('processing_status', models.CharField(choices=utils.enum.ProcessingStatus.choices, db_index=True, default='pending', max_length=12)),
                ('processing_error', models.TextField(blank=True)),
                ('alt_text', models.CharField(blank=True, max_length=500)),
                ('caption', models.TextField(blank=True)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'media',
                'verbose_name_plural': 'media',
                'db_table': 'media_media',
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='medias.collection')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_memberships', to='medias.media')),
            ],
            options={
                'db_table': 'media_collection_item',
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='cover_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_covers', to='medias.media'),
        ),
        migrations.CreateModel(
            name='MediaVariant',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="e.g. 'thumbnail', 'medium', 'hls_720p'", max_length=40)),
                ('storage_key', models.CharField(max_length=512, unique=True)),
                ('cdn_url', models.TextField(blank=True)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='medias.media')),
            ],
            options={
                'db_table': 'media_variant',
            },
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['owner', 'media_type'], name='media_owner_type_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['owner', 'processing_status'], name='media_owner_ready_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='media_search_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionitem',
            index=models.Index(fields=['collection', 'position'], name='collitem_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collectionitem',
            unique_together={('collection', 'media')},
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['owner', 'is_public'], name='collection_owner_public_idx'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='collection_search_gin_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mediavariant',
            unique_together={('media', 'label')},
        ),
    ]
