# Generated by Django 6.0.5 on 2026-06-20 15:21

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.TextField(max_length=500)),
                ('poll_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], default='single_choice', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed')], db_index=True, default='active', max_length=10)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('show_results', models.BooleanField(default=True, help_text='Allow anyone to see results before the poll ends.')),
                ('show_voters', models.BooleanField(default=False, help_text='Show who voted to the public.')),
                ('show_vote_counts', models.BooleanField(default=True, help_text='Display vote counts per option.')),
                ('show_view_counts', models.BooleanField(default=True, help_text='Display total view count.')),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('options_count', models.PositiveSmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
                ('media', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polls', to='medias.media')),
            ],
            options={
                'verbose_name': 'poll',
                'db_table': 'polls_poll',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('text', models.CharField(max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'verbose_name': 'poll option',
                'db_table': 'polls_option',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PollView',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Fallback viewer identity when unauthenticated.', null=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='polls.poll')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='poll_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'poll view',
                'db_table': 'polls_view',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.poll')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote',
                'db_table': 'polls_vote',
            },
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['author', '-created_at'], name='poll_author_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['status', '-created_at'], name='poll_active_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(condition=models.Q(('is_deleted', False), ('status', 'active')), fields=['-created_at'], name='poll_public_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='poll_created_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='polloption',
            index=models.Index(fields=['poll', 'position'], name='pollopt_order_idx'),
        ),
        migrations.AddIndex(
            model_name='pollview',
            index=models.Index(fields=['poll', 'viewer'], name='view_poll_viewer_idx'),
        ),
        migrations.AddIndex(
            model_name='pollview',
            index=models.Index(fields=['poll', '-created_at'], name='view_poll_date_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['poll', 'voter'], name='vote_poll_voter_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['option', 'voter'], name='vote_option_voter_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter', '-created_at'], name='vote_voter_history_idx'),
        ),
    ]
