# Generated by Django 6.0.5 on 2026-08-27 06:45

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Leave blank to fall back to the environment value.')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('json', 'JSON'), ('csv', 'Comma-separated list')], default='string', max_length=10)),
                ('category', models.CharField(choices=[('OTP & Authentication', 'OTP & Authentication'), ('Email', 'Email'), ('SMS & WhatsApp', 'SMS & WhatsApp'), ('Media Storage', 'Media Storage'), ('Payments', 'Payments'), ('Media Processing', 'Media Processing'), ('Advertisements', 'Advertisements'), ('Third-party Integrations', 'Third-party Integrations')], db_index=True, default='OTP & Authentication', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Uncheck to ignore this row and use the .env value instead.')),
            ],
            options={
                'verbose_name': 'setting',
                'verbose_name_plural': 'settings',
                'db_table': 'config_setting',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['is_active', 'key'], name='config_active_key_idx')],
            },
        ),
    ]
