# Generated by Django 6.0.5 on 2026-08-26 18:31

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=140)),
                ('caption', models.TextField(blank=True, max_length=1000)),
                ('call_to_action', models.CharField(choices=[('none', 'None'), ('learn_more', 'Learn More'), ('shop_now', 'Shop Now'), ('sign_up', 'Sign Up'), ('download', 'Download'), ('book_now', 'Book Now'), ('contact_us', 'Contact Us'), ('get_offer', 'Get Offer'), ('watch_more', 'Watch More')], default='learn_more', max_length=20)),
                ('destination_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('objective', models.CharField(choices=[('brand_awareness', 'Brand Awareness'), ('reach', 'Reach'), ('traffic', 'Traffic'), ('engagement', 'Engagement'), ('app_installs', 'App Installs'), ('lead_generation', 'Lead Generation'), ('conversions', 'Conversions')], default='brand_awareness', max_length=20)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1-10. Higher wins when several adverts fit one slot.', validators=[django.core.validators.MinValueValidator(1)])),
                ('daily_impression_cap', models.PositiveIntegerField(default=0, help_text='0 = uncapped.')),
                ('total_impression_cap', models.PositiveIntegerField(default=0, help_text='0 = uncapped.')),
                ('frequency_cap_per_user', models.PositiveSmallIntegerField(default=0, help_text='Max impressions per user per day. 0 = uncapped.')),
                ('target_gender', models.CharField(choices=[('all', 'All'), ('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='all', max_length=10)),
                ('target_min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('target_countries', models.JSONField(blank=True, default=list, help_text='ISO country codes; empty = everywhere.')),
                ('target_cities', models.JSONField(blank=True, default=list)),
                ('target_interests', models.JSONField(blank=True, default=list)),
                ('pricing_model', models.CharField(choices=[('cpm', 'Cpm'), ('cpc', 'Cpc'), ('cpa', 'Cpa'), ('flat', 'Flat')], default='cpm', max_length=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('impressions_count', models.PositiveBigIntegerField(default=0)),
                ('clicks_count', models.PositiveBigIntegerField(default=0)),
                ('conversions_count', models.PositiveBigIntegerField(default=0)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advertisements_advertisement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdPlacement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('flash', 'Flash'), ('on_startup', 'On Startup'), ('on_feed_list', 'On Feed List'), ('on_comment_show', 'On Comment Show'), ('on_display_view', 'On Display View'), ('on_chat_list', 'On Chat List'), ('on_search_result', 'On Search Result'), ('on_profile_view', 'On Profile View'), ('on_poll_result', 'On Poll Result'), ('on_ticket_checkout', 'On Ticket Checkout'), ('on_exit', 'On Exit')], db_index=True, max_length=30)),
                ('screen_position', models.CharField(choices=[('top', 'Top'), ('header', 'Header'), ('inline', 'Inline'), ('middle', 'Middle'), ('bottom', 'Bottom'), ('footer', 'Footer'), ('full_screen', 'Full Screen'), ('floating', 'Floating'), ('sidebar', 'Sidebar')], default='inline', max_length=20)),
                ('display_seconds', models.PositiveSmallIntegerField(default=0)),
                ('is_skippable', models.BooleanField(default=True)),
                ('skip_after_seconds', models.PositiveSmallIntegerField(default=5)),
                ('show_every_n', models.PositiveSmallIntegerField(default=1)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='advertisements.advertisement')),
            ],
            options={
                'db_table': 'advertisements_ad_placement',
                'ordering': ['mode'],
            },
        ),
        migrations.CreateModel(
            name='AdEvent',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('impression', 'Impression'), ('viewable_impression', 'Viewable Impression'), ('click', 'Click'), ('skip', 'Skip'), ('close', 'Close'), ('conversion', 'Conversion')], db_index=True, max_length=25)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('dedupe_key', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_events', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='advertisements.adplacement')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='advertisements.advertisement')),
            ],
            options={
                'db_table': 'advertisements_ad_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdDailyMetric',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('spend', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='advertisements.advertisement')),
            ],
            options={
                'db_table': 'advertisements_ad_daily_metric',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AdCreative',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=140)),
                ('caption', models.TextField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=250)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_creatives', to='medias.media')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='advertisements.advertisement')),
            ],
            options={
                'db_table': 'advertisements_ad_creative',
                'ordering': ['position'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='ad_serving_window_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['advertiser', '-created_at'], name='ad_advertiser_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status', '-priority'], name='ad_status_priority_idx'),
        ),
        migrations.AddConstraint(
            model_name='advertisement',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ad_ends_after_start'),
        ),
        migrations.AddIndex(
            model_name='adplacement',
            index=models.Index(fields=['mode', 'screen_position'], name='ad_placement_mode_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adplacement',
            unique_together={('advertisement', 'mode')},
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['advertisement', 'event_type', '-created_at'], name='ad_event_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='adevent',
            index=models.Index(fields=['advertisement', 'user', '-created_at'], name='ad_event_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='adevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__gt', '')), fields=('advertisement', 'dedupe_key'), name='ad_event_dedupe_unique'),
        ),
        migrations.AddIndex(
            model_name='addailymetric',
            index=models.Index(fields=['advertisement', '-date'], name='ad_metric_ad_date_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='addailymetric',
            unique_together={('advertisement', 'date')},
        ),
        migrations.AddIndex(
            model_name='adcreative',
            index=models.Index(fields=['advertisement', 'position'], name='ad_creative_order_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adcreative',
            unique_together={('advertisement', 'media')},
        ),
    ]
