# Generated by Django 6.0.5 on 2026-06-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_unread_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_inbox_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_created_brin_idx',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
