# Generated by Django 6.0.5 on 2026-08-27 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models



# Moves existing post coordinates into the shared snapshot table.
def copy_post_locations(apps, schema_editor):
    Post = apps.get_model("social", "Post")
    SocialLocation = apps.get_model("social", "SocialLocation")

    tagged = Post.objects.exclude(latitude=None).exclude(longitude=None).only(
        "id", "latitude", "longitude", "location_label"
    )
    for post in tagged.iterator(chunk_size=500):
        location = SocialLocation.objects.create(
            latitude=post.latitude,
            longitude=post.longitude,
            cell_key=f"{post.latitude:.4f},{post.longitude:.4f}",
            label=post.location_label or "",
            status="pending",
        )
        Post.objects.filter(pk=post.pk).update(location=location)


# Reverse: puts the coordinates back on the post.
def drop_post_locations(apps, schema_editor):
    Post = apps.get_model("social", "Post")
    for post in Post.objects.exclude(location=None).select_related("location").iterator(
        chunk_size=500
    ):
        Post.objects.filter(pk=post.pk).update(
            latitude=post.location.latitude,
            longitude=post.location.longitude,
            location_label=post.location.label,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_notification_notif_unread_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLocation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('cell_key', models.CharField(db_index=True, max_length=32)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('formatted_address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'social_location',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cell_key', 'status'], name='social_loc_cell_idx')],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='social.sociallocation'),
        ),
        migrations.AddField(
            model_name='like',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='like_set', to='social.sociallocation'),
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='social.sociallocation'),
        ),
        migrations.AddField(
            model_name='reshare',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_set', to='social.sociallocation'),
        ),
        migrations.RunPython(copy_post_locations, drop_post_locations),
        migrations.RemoveField(
            model_name='post',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location_label',
        ),
        migrations.RemoveField(
            model_name='post',
            name='longitude',
        ),
    ]
