# Generated by Django 6.0.5 on 2026-06-28 04:10

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import utils.generators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0003_group_join_request'),
        ('medias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_icons', to='medias.media')),
            ],
            options={
                'verbose_name': 'event category',
                'verbose_name_plural': 'event categories',
                'db_table': 'tickets_event_category',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('platform_name', models.CharField(help_text='Venue or platform name (e.g. Zoom, Google Meet, Eko Hotels)', max_length=200)),
                ('website_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, help_text='Physical venue address if applicable', max_length=300)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private_link', 'Private Link')], db_index=True, default='public', max_length=20)),
                ('fee_bearer', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=10)),
                ('pricing_mode', models.CharField(choices=[('flat', 'Flat'), ('categorized', 'Categorized')], default='flat', max_length=15)),
                ('qr_code', models.TextField(blank=True, help_text='Base64 or URL to event QR image')),
                ('event_link', models.CharField(db_index=True, default=utils.generators.generate_event_link, max_length=64, unique=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False, help_text='Verified badge — set by admin')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='draft', max_length=15)),
                ('total_tickets_sold', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tickets_available', models.PositiveIntegerField(default=0)),
                ('tickets_reserved', models.PositiveIntegerField(default=0)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_covers', to='medias.media')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='tickets.eventcategory')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'db_table': 'tickets_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PriceTier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_tag', models.CharField(choices=[('general', 'General'), ('vip', 'Vip'), ('regular', 'Regular'), ('gold', 'Gold')], default='general', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
                ('quantity_reserved', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='tickets.event')),
            ],
            options={
                'verbose_name': 'price tier',
                'db_table': 'tickets_price_tier',
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('business_name', models.CharField(max_length=200)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_phone', models.CharField(blank=True, max_length=30)),
                ('business_address', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], db_index=True, default='not_submitted', max_length=20)),
                ('document_type', models.CharField(blank=True, choices=[], max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Platform commission percentage (e.g. 5.00 = 5%)', max_digits=5)),
                ('total_events_created', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('back_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_kyc_back', to='medias.media')),
                ('front_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_kyc_front', to='medias.media')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reviews', to=settings.AUTH_USER_MODEL)),
                ('selfie_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_kyc_selfie', to='medias.media')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'seller profile',
                'db_table': 'tickets_seller_profile',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees_deducted', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('payout_ref', models.CharField(db_index=True, max_length=32, unique=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, help_text='Null if aggregated multiple events', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='tickets.event')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='tickets.sellerprofile')),
            ],
            options={
                'verbose_name': 'payout',
                'db_table': 'tickets_payout',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tickets.sellerprofile'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_code', models.CharField(db_index=True, default=utils.generators.generate_ticket_code, max_length=20, unique=True)),
                ('qr_code_data', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('sold', 'Sold'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='reserved', max_length=12)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fees_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_verified', models.BooleanField(default=False, help_text='Custom verified badge on the ticket')),
                ('purchased_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_tickets', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.event')),
                ('price_tier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.pricetier')),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets_ticket',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('refund', 'Refund'), ('fee', 'Fee'), ('payout', 'Payout')], db_index=True, max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('reference', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='successful', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_logs', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tickets.event')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='tickets.sellerprofile')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'db_table': 'tickets_transaction',
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(choices=[('ticket_not_delivered', 'Ticket Not Delivered'), ('event_cancelled', 'Event Cancelled'), ('wrong_description', 'Wrong Description'), ('refund_request', 'Refund Request'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved_buyer', 'Resolved Buyer'), ('resolved_seller', 'Resolved Seller'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_disputes', to=settings.AUTH_USER_MODEL)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_disputes', to=settings.AUTH_USER_MODEL)),
                ('conversation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute', to='chats.conversation')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tickets.event')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tickets.sellerprofile')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='tickets.ticket')),
            ],
            options={
                'verbose_name': 'dispute',
                'verbose_name_plural': 'disputes',
                'db_table': 'tickets_dispute',
            },
        ),
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fees_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded')], db_index=True, default='pending', max_length=20)),
                ('transaction_ref', models.CharField(db_index=True, max_length=64, unique=True)),
                ('paystack_access_code', models.CharField(blank=True, max_length=64)),
                ('paystack_authorization_url', models.URLField(blank=True)),
                ('paystack_data', models.JSONField(blank=True, default=dict, help_text='Raw Paystack response/event data for audit')),
                ('reserved_until', models.DateTimeField(blank=True, db_index=True, help_text='Tickets reserved until this timestamp, then released', null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_purchases', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tickets.event')),
            ],
            options={
                'verbose_name': 'ticket purchase',
                'db_table': 'tickets_purchase',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.ticketpurchase'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['name'], name='cat_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='pricetier',
            index=models.Index(fields=['event', 'is_active'], name='pricetier_event_active_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricetier',
            unique_together={('event', 'price_tag')},
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['status'], name='seller_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['user'], name='seller_active_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['seller', '-created_at'], name='payout_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['event', 'status'], name='payout_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['seller', '-created_at'], name='event_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['status', '-created_at'], name='event_active_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(condition=models.Q(('is_deleted', False), ('status', 'published')), fields=['-created_at'], name='event_public_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='event_created_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['seller', '-created_at'], name='tx_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['seller', 'transaction_type'], name='tx_seller_type_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=models.Index(fields=['reference'], name='tx_reference_idx'),
        ),
        migrations.AddIndex(
            model_name='paymenttransaction',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='tx_created_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='dispute_status_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['buyer', 'status'], name='dispute_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['seller', 'status'], name='dispute_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['buyer', '-created_at'], name='purchase_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['event', 'payment_status'], name='purchase_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketpurchase',
            index=models.Index(fields=['transaction_ref'], name='purchase_ref_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['event', 'status'], name='ticket_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['buyer', '-purchased_at'], name='ticket_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_code'], name='ticket_code_idx'),
        ),
    ]
