# Generated by Django 6.0.5 on 2026-06-06 17:08

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import utils.enum
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('notification_type', models.CharField(choices=utils.enum.NotificationType.choices, db_index=True, max_length=30)),
                ('category', models.CharField(choices=utils.enum.NotificationCategory.choices, db_index=True, help_text='Derived from notification_type. Stored for fast preference lookup.', max_length=15)),
                ('priority', models.CharField(choices=utils.enum.NotificationPriority.choices, db_index=True, default='normal', max_length=8)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, max_length=1000)),
                ('action_url', models.CharField(blank=True, help_text='Client-side deep link, e.g. /posts/uuid or /profile/username', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary JSON payload for client rendering.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_push', models.BooleanField(default=False, help_text='True after FCM/APNs push was dispatched.')),
                ('sent_push_at', models.DateTimeField(blank=True, null=True)),
                ('is_sent_ws', models.BooleanField(default=False, help_text='True after WebSocket delivery confirmed.')),
                ('sent_ws_at', models.DateTimeField(blank=True, null=True)),
                ('group_key', models.CharField(blank=True, db_index=True, help_text='Grouping key for collapsible notifications.', max_length=200)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttachment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attachment_type', models.CharField(choices=utils.enum.NotificationAttachmentType.choices, default='image', max_length=12)),
                ('cdn_url', models.TextField(help_text='Full CDN URL of the image.')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Display order when multiple attachments present.')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notifications.notification')),
            ],
            options={
                'db_table': 'notifications_attachment',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_key', models.CharField(db_index=True, max_length=200)),
                ('actor_ids', models.JSONField(default=list, help_text='First 3 actor UUIDs for preview.')),
                ('total_count', models.PositiveIntegerField(default=1)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('last_event_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('latest_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='notifications.notification')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications_batch',
            },
        ),
        migrations.CreateModel(
            name='NotificationMute',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mute_type', models.CharField(choices=utils.enum.NotificationMuteType.choices, db_index=True, max_length=10)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('muted_category', models.CharField(blank=True, choices=utils.enum.NotificationCategory.choices, max_length=15)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='null = permanent. Set for timed mutes.', null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('muted_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='muted_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification mute',
                'db_table': 'notifications_mute',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=utils.enum.NotificationCategory.choices, db_index=True, max_length=15)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification preference',
                'db_table': 'notifications_preference',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notif_recipient_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('is_deleted', False), ('is_read', False)), fields=['recipient', 'is_read'], name='notif_unread_partial_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'category', '-created_at'], name='notif_recipient_category_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['actor', 'notification_type'], name='notif_actor_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['group_key', '-created_at'], name='notif_group_key_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['created_at'], name='notifification_created_brin_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationattachment',
            index=models.Index(fields=['notification', 'position'], name='notif_attach_order_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(fields=['recipient', '-last_event_at'], name='batch_recipient_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationbatch',
            index=models.Index(condition=models.Q(('is_read', False)), fields=['recipient'], name='batch_unread_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationbatch',
            unique_together={('recipient', 'group_key')},
        ),
        migrations.AddIndex(
            model_name='notificationmute',
            index=models.Index(fields=['user', 'mute_type'], name='mute_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmute',
            index=models.Index(fields=['user', 'muted_actor'], name='mute_user_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationmute',
            index=models.Index(fields=['expires_at'], name='mute_expires_at_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['user', 'category'], name='notifpref_user_cat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'category')},
        ),
    ]
